# Основной сервер
server:

    # Логи (по желанию)
    # Минимальные логи. Можно увеличить до 2–3 для отладки.
    verbosity: 2
    logfile: ""
    #use-syslog: yes

    port: 53
    do-ip4: yes
    do-ip6: no
    do-udp: yes
    do-tcp: yes
    
    # Слушать на всех интерфейсах
    interface: 0.0.0.0
    interface-automatic: no
    
    # Кеш
#    cache-min-ttl: 600
#    cache-max-ttl: 86400
#    prefetch: yes
#    prefetch-key: yes
    
    # Безопасность
    hide-identity: yes
    hide-version: yes
    harden-glue: yes
    harden-dnssec-stripped: yes
    harden-below-nxdomain: yes
    harden-referral-path: yes
    unwanted-reply-threshold: 10000000
    
    # Приватные сети
    #private-address: 10.0.0.0/8
    private-address: 127.0.0.0/8
    private-address: 172.16.0.0/12
    #private-address: 192.168.0.0/16
    #private-address: 169.254.0.0/16

    # Разрешить запросы из локальной сети
    #access-control: 10.0.0.0/8 allow
    access-control: 127.0.0.0/8 allow
    access-control: 172.16.0.0/12 allow
    access-control: 192.168.0.0/16 allow
    access-control: 10.0.0.0/8 allow
    access-control: 0.0.0.0/0 refuse

    # DNSSEC
    tls-cert-bundle: "/etc/ssl/certs/ca-certificates.crt"

    # защита от подмены ответов; harden-dnssec-stripped запрещает ответы без валидной подписи
    harden-dnssec-stripped: yes


forward-zone:
    name: "."
    forward-tls-upstream: yes
    forward-addr: 8.8.8.8@853#dns.google
    forward-addr: 8.8.4.4@853#dns.google
    forward-addr: 1.1.1.1@853#cloudflare-dns.com
    forward-addr: 1.0.0.1@853#cloudflare-dns.com


#forward-zone:
#    name: "."
#    forward-addr: 127.0.0.1@9053


forward-zone:
    name: "ru."
    forward-tls-upstream: yes
    forward-addr: 77.88.8.8@853#common.dot.dns.yandex.net
    forward-addr: 77.88.8.1@853#common.dot.dns.yandex.net
