services:
  iptables-init:
    image: alpine:latest
    container_name: home_proxy-iptables-init
    privileged: true
    network_mode: host # Доступ к сети хоста для управления iptables
    volumes:
      - ./apply-iptables.sh:/apply-iptables.sh:ro
    command: ["sh", "-c", "apk add --no-cache iptables bash && bash /apply-iptables.sh apply"]
    restart: "no" # Автозапуск при старте системы

  unbound:
    build:
      context: ./unbound
      dockerfile: Dockerfile
    container_name: home_proxy-unbound
    restart: unless-stopped
    ports:
      - "$UNBOUND_PORT:53/tcp"
      - "$UNBOUND_PORT:53/udp"
    volumes:
      - ./unbound/config/unbound.conf:/etc/unbound/unbound.conf
#    networks:
#      - $DOCKER_NETWORK
    command: unbound -d -c /etc/unbound/unbound.conf

  tor:
    build:
      context: ./tor
      dockerfile: Dockerfile
    container_name: home_proxy-tor
    restart: unless-stopped
    ports:
      - $TOR_SOCKS_PORT:9050/tcp
#    networks:
#      - $DOCKER_NETWORK
    volumes:
      - ./tor/config/torrc:/etc/tor/torrc
      - ./tor/config/bridges.txt:/etc/tor/bridges.txt
      - ./tor/data:/var/lib/tor
    environment:
      - PROJECT_GID=${PROJECT_GID:-1000}
      - HOST_GROUP_NAME=${HOST_GROUP_NAME:-project}


  privoxy:
    build:
      context: ./privoxy
      dockerfile: Dockerfile
    container_name: home_proxy-privoxy
    restart: unless-stopped
    ports:
      - "$PRIVOXY_PORT:8118"
    volumes:
      - ./privoxy/config/config:/etc/privoxy/config
      - ./privoxy/config/match-all.action:/etc/privoxy/match-all.action
      - ./privoxy/config/user.action:/etc/privoxy/user.action
      - ./privoxy/config/default.action:/etc/privoxy/default.action

  squid:
    build:
      context: ./squid
      dockerfile: Dockerfile
    container_name: home_proxy-squid
    volumes:
      - ./squid/config/squid.conf:/etc/squid/squid.conf
      - ./squid/config/tor.list:/etc/squid/tor.list
      - ./squid/config/tor_dst.list:/etc/squid/tor_dst.list
      - ./squid/ssl:/etc/squid/ssl
      - squid_cache:/var/spool/squid
    network_mode: host
    restart: unless-stopped

#networks:
#  proxy_network:
#    driver: bridge

volumes:
  squid_cache:
