events {
    multi_accept on;
    worker_connections 1024;
}

http {
    access_log /dev/stdout;
    error_log /dev/stderr;

    map $http_upgrade $connection_upgrade {
        default upgrade;
        '' close;
    }

    include /etc/nginx/conf/*.conf;
}
