#acl localnet src 192.168.1.0/24		# RFC 1918 local private network (LAN)
acl localnet src 172.16.0.0/12		# RFC 1918 local private network (LAN)

acl SSL_ports port 443
acl Safe_ports port 80		# http
acl Safe_ports port 21		# ftp
acl Safe_ports port 443		# https
acl Safe_ports port 70		# gopher
acl Safe_ports port 210		# wais
acl Safe_ports port 1025-65535	# unregistered ports
acl Safe_ports port 280		# http-mgmt
acl Safe_ports port 488		# gss-http
acl Safe_ports port 591		# filemaker
acl Safe_ports port 777		# multiling http

http_access deny !Safe_ports
http_access deny CONNECT !SSL_ports
http_access allow localhost manager
http_access deny manager

http_access deny to_localhost
http_access deny to_linklocal

http_port 3128
http_port 8081 transparent
https_port 8082 intercept ssl-bump generate-host-certificates=off cert=/etc/squid/ssl/squidCA.crt key=/etc/squid/ssl/squidCA.key


acl tor_url ssl::server_name_regex "/etc/squid/tor.list"
acl step1 at_step SslBump1
ssl_bump peek step1
ssl_bump splice all


always_direct allow !tor_url
never_direct allow tor_url

http_access allow localhost
http_access allow localnet

http_access deny all

#coredump_dir /var/cache/squid

# refresh_pattern ^ftp:		1440	20%	10080
# refresh_pattern -i (/cgi-bin/|\?) 0	0%	0
# refresh_pattern .		0	20%	4320
# refresh_pattern -i \.jpg$ 1440 90% 10080
# refresh_pattern -i \.png$ 1440 90% 10080
# refresh_pattern -i \.css$ 60 20% 1440
# refresh_pattern -i \.js$ 60 20% 1440

server_persistent_connections on
client_persistent_connections on
read_timeout 5 minutes
#connect_timeout 60 seconds
connect_timeout 5 minutes

workers 1   # количество процессов зависит от CPU

# Кеш
maximum_object_size 1024 MB
memory_replacement_policy heap GDSF
cache_mem 64 MB      # или больше, если есть RAM
cache_peer privoxy parent 8118 0 no-query no-digest default

# Сруб логов
access_log none
cache_store_log none
cache_log /dev/null
